name: Deploy Financial Analysis App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Set OpenAI API Key
        env:
          openai_api_key: ${{ secrets.openai_api_key }}
        run: |
          echo "API Key Set in Environment Variable"

      - name: Run the app
        run: |
         python main.py  # Replace with your script or command to run your app
